### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by livthomas** [sindresorhus/leven#21]
I'm getting the following error when trying to use this library in my Electron project:
```
[0] App threw an error during load
[0] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/livthomas/Projects/my-project/node_modules/leven/index.js
[0] require() of ES modules is not supported.
[0] require() of /home/livthomas/Projects/my-project/node_modules/leven/index.js from /home/livthomas/Projects/my-project/build/utils/string/areStringsSimilar.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[0] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/livthomas/Projects/my-project/node_modules/leven/package.json.
[0] 
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
[0]     at Module.load (internal/modules/cjs/loader.js:935:32)
[0]     at Module._load (internal/modules/cjs/loader.js:776:14)
[0]     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
[0]     at Module.require (internal/modules/cjs/loader.js:959:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/home/livthomas/Projects/my-project/build/utils/string/areStringsSimilar.js:7:33)
[0]     at Module._compile (internal/modules/cjs/loader.js:1078:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[0]     at Module.load (internal/modules/cjs/loader.js:935:32)
```
I'm not sure whether this is some obvious bug that can be addressed by the author of this library or it is wrong configuration on my side. I have been developing this project for a year and I haven't encountered anything similar with any other library. And from the output it looks like the recommended solution is to update something in this library.

My project environment:
* Node.js 16.11.1
* Electron 13.5.2
* TypeScript 4.5.2

**Comment by sindresorhus** [comment]
Electron does not yet support ESM.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Reply2Zain** [comment]
If you come across this error while using node.js try using `leven: ^3.1.0`.
